package newworldorder.game.model;

/**
 * ColourType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum ColourType {
    RED,
    GREEN,
    BLUE,
    YELLOW,
    PURPLE,
    ORANGE,
    BROWN,
    PINK
}
