package newworldorder.game.model;

/**
 * MoveType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum MoveType {
    INVALIDMOVE,
    FREEMOVE,
    CLEARTOMB,
    GATHERWOOD,
    NEUTRALTAKEOVER,
    ENEMYTAKEOVER,
    COMBINEUNITS,
    TRAMPLEMEADOW
}
