package newworldorder.client.shared;

public enum UIActionType {
	MOVEUNIT,
	BUILDROAD,
	CULTIVATEMEADOW,
	BUILDTOWER,
	BUILDUNITPEASANT,
	BUILDUNITSOLDIER,
	BUILDUNITINFANTRY,
	BUILDUNITKNIGHT,
	UPGRADEUNITSOLDIER,
	UPGRADEUNITINFANTRY,
	UPGRADEUNITKNIGHT,
	UPGRADEVILLAGETOWN,
	UPGRADEVILLAGEFORT,
	ENDTURN
}
