package newworldorder.client.shared;

/**
 * VillageType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum VillageType {
    HOVEL,
    TOWN,
    FORT,
    CASTLE
}
