package newworldorder.client.model;

/**
 * ActionType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum ActionType {
    READYFORORDERS,
    MOVED,
    BUILDINGROAD,
    CHOPPINGTREE,
    CLEARINGTOMBSTONE,
    UPGRADINGCOMBINING,
    STARTCULTIVATING,
    FINISHCULTIVATING
}
