package newworldorder.client.model;

/**
 * MoveType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
enum MoveType {
    INVALIDMOVE,
    FREEMOVE,
    CLEARTOMB,
    GATHERWOOD,
    NEUTRALTAKEOVER,
    ENEMYTAKEOVER,
    COMBINEUNITS,
    TRAMPLEMEADOW
}
