package newworldorder.client.model;

/**
 * StructureType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum StructureType {
    ROAD,
    WATCHTOWER,
    TOMBSTONE
}
