package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Clock class definition.
 * Generated by the TouchCORE code generator.
 */
public class Clock {
    
    private Date now;
    
    public Date getNow() {
        /* TODO: No message view defined */
        return null;
    }
}
