package ca.mcgill.cs.comp361.nwo.mwgs.model;

import java.util.ArrayList;
import java.util.List;



/**
 * Game class definition.
 * Generated by the TouchCORE code generator.
 */
public class Game {
    
    private int roundCount;
    private boolean hasWon;
    private List<Player> players;
    private List<Message> chat;
    private Player turnOf;
    private Map map;
    
    public Game() {
        /* TODO: No message view defined */
    }

    public Map getMap() {
        /* TODO: No message view defined */
        return null;
    }

    public void setMap(Map map) {
        /* TODO: No message view defined */
    }

    public ArrayList<Player> getPlayers() {
        /* TODO: No message view defined */
        return null;
    }

    public void setPlayers(List<Player> players) {
        /* TODO: No message view defined */
    }

    public int getRoundCount() {
        /* TODO: No message view defined */
        return 0;
    }

    public void setRoundCount(int roundCount) {
        /* TODO: No message view defined */
    }

    public Player getTurnOf() {
        /* TODO: No message view defined */
        return null;
    }

    public void setTurnOf(Player turnOf) {
        /* TODO: No message view defined */
    }

    public boolean hasWon() {
        /* TODO: No message view defined */
        return false;
    }

    public void setHasWon(boolean hasWon) {
        /* TODO: No message view defined */
    }
}
