package ca.mcgill.cs.comp361.nwo.mwgs.model;

import java.util.List;



/**
 * JsonMapParser class definition.
 * Generated by the TouchCORE code generator.
 */
public class JsonParser {
    
    public static List<Tile> parseTiles(String jsonMap, Map map) {
        /* TODO Implement */
        //This operation returns a sequnce of tiles parsed from the JSON string representation of the map;
        //The tiles that are created only have terrain set, there are no villages yet;
        return null;
    }
    
    public static Map parseMap(String jsonMap) {
        /* TODO Implement */
        Map map = null;
        List<Tile> parsedTiles = parseTiles(null, map);
        for (Tile t : parsedTiles) {
            // This loop randomly places an equal number of villages for each player then creates a randomly sized region around the village;
            // The parameters used below are not what they will be in implementation, there will be more logic to select players and tiles;
            // village = new Village();
            // village.setControlledBy();
            // region = new Region();
            // region.setVillage(village);
            // region.addTile();
        }
        return null;
    }
    
}
