package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * JsonMapParser class definition.
 * Generated by the TouchCORE code generator.
 */
public class JsonMapParser {
    
    public static List<Tile> parseTiles(String jsonMap) {
        This operation returns a sequnce of tiles parsed from the JSON string representation of the map;
        The tiles that are created only have terrain set, there are no villages yet;
        return ;
    }
}
