package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Message class definition.
 * Generated by the TouchCORE code generator.
 */
public class Message {
    
    private String message;
    private Date timestamp;
    private Player sender;
    
    public Message(String message, Player sender) {
        /* TODO: No message view defined */
    }

    public String getMessage() {
        /* TODO: No message view defined */
        return "";
    }

    public Player getSender() {
        /* TODO: No message view defined */
        return null;
    }

    public Date getTimestamp() {
        /* TODO: No message view defined */
        return null;
    }
}
