package ca.mcgill.cs.comp361.nwo.mwgs.model;

import java.util.List;



/**
 * Region class definition.
 * Generated by the TouchCORE code generator.
 */
public class Region {
    
    private List<Tile> tiles;
    private Village controllingVillage;
    
    public Region(List<Tile> tiles) {
        /* TODO: No message view defined */
    }

    public void destroy() {
        /* TODO: No message view defined */
    }

    public void removeTile(Tile t) {
        /* TODO: No message view defined */
    }

    public void addTile(Tile t) {
        /* TODO: No message view defined */
    }

    public List<Tile> getTiles() {
        /* TODO: No message view defined */
        return null;
    }

    public Village getVillage() {
        /* TODO: No message view defined */
        return null;
    }

    public void setVillage(Village myVillage) {
        /* TODO: No message view defined */
    }

    public Player getControllingPlayer() {
        Player controlledBy;
        controlledBy = controllingVillage.getControlledBy();
        return controlledBy;
    }

    public int getTileCount(TerrainType t) {
        TerrainType terrainType;
        total = 0;
        for (int i = 1 to tiles.size()) {
            terrainType = tiles.getTerrainType();
            return terrainType;
            if (terrainType == t) {
                total++;
            }
        }
        return total;
        return 0;
    }

    public void createVillage() {
        Village village;
        if (controllingVillage == null) {
            //Randomly select a tile in the region that is a grass terrain.;
            //Place a new village on that tile.;
            village = new Village();
            tiles.setVillage(village);
        }
    }
}
