package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Structure class definition.
 * Generated by the TouchCORE code generator.
 */
public class Structure {
    
    private StructureType type;
    private Tile tile;
    
    public Structure(StructureType type) {
        /* TODO: No message view defined */
    }

    public void destroy() {
        /* TODO: No message view defined */
    }

    public Tile getTile() {
        /* TODO: No message view defined */
        return null;
    }

    public void setTile(Tile tile) {
        /* TODO: No message view defined */
    }

    public StructureType getType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setType(StructureType type) {
        /* TODO: No message view defined */
    }
}
