package ca.mcgill.cs.comp361.nwo.mwgs.model;

/**
 * TerrainType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum TerrainType {
    SEA,
    GRASS,
    TREE,
    MEADOW
}
