package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public class Tile {
    
    private TerrainType terrainType;
    private int x;
    private int y;
    private List<Tile> neighbour;
    private Region region;
    private Unit unit;
    private Village myVillage;
    private Structure occupyingStructure;
    private Map map;
    
    public Tile(int x, int y, Map myMap) {
        /* TODO: No message view defined */
    }

    public void setStructure(Structure structure) {
        /* TODO: No message view defined */
    }

    public Village getVillage() {
        /* TODO: No message view defined */
        return null;
    }

    public Region getRegion() {
        /* TODO: No message view defined */
        return null;
    }

    public Unit getUnit() {
        /* TODO: No message view defined */
        return null;
    }

    public void setUnit(Unit unit) {
        /* TODO: No message view defined */
    }

    public TerrainType getTerrainType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setTerrainType(TerrainType type) {
        /* TODO: No message view defined */
    }

    public void setVillage(Village myVillage) {
        /* TODO: No message view defined */
    }

    public Structure getStructure() {
        /* TODO: No message view defined */
        return null;
    }

    public List<Tile> getNeighbours() {
        /* TODO: No message view defined */
        return null;
    }

    public void killUnit() {
        /* TODO: No message view defined */
    }

    public void setRegion(Region region) {
        /* TODO: No message view defined */
    }

    public Player getControllingPlayer() {
        Player controllingPlayer;
        if (if region != null) {
            controllingPlayer = region.getControllingPlayer();
            return controllingPlayer;
        }
        return ;
    }

    public int hashCode() {
        return y * width + x;
        return 0;
    }
}
