package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Unit class definition.
 * Generated by the TouchCORE code generator.
 */
public class Unit {
    
    private UnitType unitType;
    private ActionType currentAction;
    private int immobileUntilRound;
    private Tile tile;
    private Village myVillage;
    
    public Unit() {
        /* TODO: No message view defined */
    }

    public void destroy() {
        /* TODO: No message view defined */
    }

    public UnitType getUnitType() {
        /* TODO: No message view defined */
        return null;
    }

    public ActionType getCurrentAction() {
        /* TODO: No message view defined */
        return null;
    }

    public void setCurrentAction(ActionType currentAction) {
        /* TODO: No message view defined */
    }

    public void setImmobileUntilRound(int pImmobileUntilRound) {
        immobileUntilRound = pImmobileUntilRound;
    }

    public Tile getTile() {
        /* TODO: No message view defined */
        return null;
    }

    public Village getVillage() {
        /* TODO: No message view defined */
        return null;
    }

    public int getUpkeep() {
        int level, cost;
        level = Unit.unitLevel(unitType);
        cost = 2 * 3 ^ (level - 1);
        return cost;
    }

    public void setUnitType(UnitType unitType) {
        /* TODO: No message view defined */
    }

    public static int unitLevel(UnitType u) {
        if (u == UnitType.PEASANT) {
            return 1;
        } else if (u == UnitType.INFANTRY) {
            return 2;
        } else if (u == UnitType.SOLDIER) {
            return 3;
        } else if (u == UnitType.KNIGHT) {
            return 4;
        }
        return -1;
    }

    public static int unitCost(UnitType u) {
        int level;
        level = Unit.unitLevel(u);
        level = level * 10;
        return level;
    }

    public void kill() {
        // This operation replaces the unit with a tombstone;
        myVillage.removeUnit(this);
        tile.setUnit(null);
        tile.setStructure(StructureType.TOMBSTONE);
        destroy();
    }

    public void setTile(Tile tile) {
        /* TODO: No message view defined */
    }

    public Player getControllingPlayer()
    {
        // TODO Auto-generated method stub
        return null;
    }
}
