package ca.mcgill.cs.comp361.nwo.mwgs.model;



/**
 * Village class definition.
 * Generated by the TouchCORE code generator.
 */
public class Village {
    
    private VillageType villageType;
    private int gold;
    private int wood;
    private Player controlledBy;
    private Tile tile;
    private Region controlledRegion;
    private List<Unit> supportedUnits;
    
    public Village() {
        /* TODO: No message view defined */
    }

    public void destroy() {
        /* TODO: No message view defined */
    }

    public int getGold() {
        /* TODO: No message view defined */
        return 0;
    }

    public int getWood() {
        /* TODO: No message view defined */
        return 0;
    }

    public void transactGold(int g) {
        gold = gold + g;
    }

    public void transactWood(int w) {
        wood = wood + w;
    }

    public Region getRegion() {
        /* TODO: No message view defined */
        return null;
    }

    public void setControlledBy(Player controlledBy) {
        /* TODO: No message view defined */
    }

    public ArrayList<Unit> getSupportedUnits() {
        /* TODO: No message view defined */
        return null;
    }

    public void addUnit(Unit u) {
        supportedUnits.add(u);
    }

    public void removeUnit(Unit u) {
        supportedUnits.remove(u);
    }

    public VillageType getVillageType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setVillageType(VillageType villageType) {
        /* TODO: No message view defined */
    }

    public static int villageLevel(VillageType v) {
        if (v == VillageType.HOVEL) {
            return 0;
        } else if (v == VillageType.TOWN) {
            return 1;
        } else if (v == VillageType.FORT) {
            return 2;
        }
        return -1;
    }

    public static int villageCost(VillageType v) {
        if (v == VillageType.HOVEL) {
            return 0;
        } else if (v == VillageType.TOWN) {
            return 8;
        } else if (v == VillageType.FORT) {
            return 16;
        }
        return -1;
    }

    public Player getControlledBy() {
        /* TODO: No message view defined */
        return null;
    }

    public int getTotalUpkeep() {
        int upkeep;
        total = 0;
        for (for int i = 1 to supportedUnits.size()) {
            upkeep = supportedUnits.getUpkeep();
            total += upkeep;
        }
        return 0;
    }

    public int getTotalIncome() {
        int grass;
        int meadow;
        total = 0;
        grass = controlledRegion.getTileCount();
        meadow = controlledRegion.getTileCount();
        total = grass + 2 * meadow;
        return total;
        return 0;
    }

    public void kill() {
        for (for each Unit u in supportUnits) {
            supportedUnits.kill();
        }
        destroy();
    }
}
