package newworldorder.client.guihandler;

/**
 * TerrainType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum TerrainType {
    SEA,
    GRASS,
    TREE,
    MEADOW
}
